-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 13:25:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `escuela` ;

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escuela` ;
USE `escuela` ;

-- -----------------------------------------------------
-- Table `escuela`.`ALUMNOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`ALUMNOS` ;

CREATE TABLE IF NOT EXISTS `escuela`.`ALUMNOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`PROFESOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`PROFESOR` ;

CREATE TABLE IF NOT EXISTS `escuela`.`PROFESOR` (
  `cid` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `ALUMNOS_id` INT NOT NULL,
  PRIMARY KEY (`cid`),
  INDEX `fk_PROFESOR_ALUMNOS_idx` (`ALUMNOS_id` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESOR_ALUMNOS`
    FOREIGN KEY (`ALUMNOS_id`)
    REFERENCES `escuela`.`ALUMNOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`MATERIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`MATERIA` ;

CREATE TABLE IF NOT EXISTS `escuela`.`MATERIA` (
  `cDeMateria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `grado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cDeMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`ALUMNOS_has_MATERIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`ALUMNOS_has_MATERIA` ;

CREATE TABLE IF NOT EXISTS `escuela`.`ALUMNOS_has_MATERIA` (
  `ALUMNOS_id` INT NOT NULL AUTO_INCREMENT,
  `MATERIA_cDeMateria` INT NOT NULL,
  PRIMARY KEY (`ALUMNOS_id`, `MATERIA_cDeMateria`),
  INDEX `fk_ALUMNOS_has_MATERIA_MATERIA1_idx` (`MATERIA_cDeMateria` ASC) VISIBLE,
  INDEX `fk_ALUMNOS_has_MATERIA_ALUMNOS1_idx` (`ALUMNOS_id` ASC) VISIBLE,
  CONSTRAINT `fk_ALUMNOS_has_MATERIA_ALUMNOS1`
    FOREIGN KEY (`ALUMNOS_id`)
    REFERENCES `escuela`.`ALUMNOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUMNOS_has_MATERIA_MATERIA1`
    FOREIGN KEY (`MATERIA_cDeMateria`)
    REFERENCES `escuela`.`MATERIA` (`cDeMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
